[package]
name = "rstore-server"
edition.workspace = true
version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
rstore-common.workspace = true
rstore-store.workspace = true
rstore-api.workspace = true
rstore-s3.workspace = true
rstore-s3-compat.workspace = true
rstore-disk.workspace = true
rstore-meta.workspace = true
tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
